### ISSUE TITLE
Add option `minimumLines` to ignore `emptyLineBefore` if group has less than specified amount of properties

### ISSUE THREAD

**Issue by thasmo** [hudochenkov/stylelint-order#10]
The given rules
```json
{
	"minimumLines": 2,
	"emptyLineBefore": "always",
	"properties": [
		"position",
		"display"
	]
},
{
	"minimumLines": 2,
	"emptyLineBefore": "always",
	"properties": [
		"font",
		"color"
	]
}
```
will warn about this: (empty line before `font-family` missing)
```css
p {
	position: relative;
	display: block;
	font-family: sans-serif;
	color: tomato;
}
```
but will be fine i.e. ignore this: (`font-family` is only 1 line of the specified group)
```css
p {
	position: relative;
	font-family: sans-serif;
}
```

That would be helpful! :) Thanks for the awesome plugin!

**Comment by hudochenkov** [comment]
I'm not sure `minimumLines` option is viable.

What it should do if there less properties than `minimumLines`? Ignore `emptyLineBefore` for this group or revert it?

If `emptyLineBefore` will be ignored, with a config above this won't be considered as warning:

```css
p {
	position: relative;
	display: block;
	font-family: sans-serif;
}
```

```css
p {
	position: relative;
	display: block;

	font-family: sans-serif;
}
```

If `emptyLineBefore` will be reverted, with a config above this won't be considered as warning:

```css
p {
	position: relative;
	display: block;
	font-family: sans-serif;
}
```

This will be a warning:

```css
p {
	position: relative;
	display: block;

	font-family: sans-serif;
}
```

With the following config and if `emptyLineBefore` will be reverted:

```json
{
	"minimumLines": 2,
	"emptyLineBefore": "never",
	"properties": [
		"position",
		"display"
	]
},
{
	"minimumLines": 2,
	"emptyLineBefore": "never",
	"properties": [
		"font",
		"color"
	]
}
```

The following patterns are considered warnings:

```css
p {
	position: relative;
	display: block;
	font-family: sans-serif;
}
```

The following patterns are _not_ considered warnings:

```css
p {
	position: relative;
	display: block;

	font-family: sans-serif;
}
```
