### ISSUE TITLE
emptyLineMinimumPropertyThreshold not working for groups

### ISSUE THREAD

**Issue by Spielboerg** [hudochenkov/stylelint-order#101]
The option `emptyLineBefore: 'threshold'` is not working with `emptyLineMinimumPropertyThreshold`.

My config (`.stylelintrc.js`):

```js
const defaultOrderConfig = {
  emptyLineBefore: 'threshold',
  emptyLineMinimumPropertyThreshold: 4,
  noEmptyLineBetween: true,
};

const PROPERTY_ORDER = [
  {
    ...defaultOrderConfig,
    groupName: 'Pseudo-Elements',
    properties: ['content'],
  },
  {
    ...defaultOrderConfig,
    groupName: 'Box',
    properties: ['position', 'display', 'visibility', 'box-sizing', 'float', 'clear'],
  },
  { /* ... more order groups */ },
  {
    ...defaultOrderConfig,
    groupName: 'Positioning',
    properties: ['top', 'right', 'bottom', 'left'],
  },
  { /* ... more order groups */ },
  {
    ...defaultOrderConfig,
    groupName: 'Background',
    properties: [
      'opacity',
      'background',
      'background-color',
      'background-image',
      'background-repeat',
      'background-position',
      'background-size',
      'box-shadow',
      'fill',
    ],
  },
  { /* ... more order groups */ },
  {
    ...defaultOrderConfig,
    groupName: 'Other',
    properties: [
      'z-index',
      'tab-size',
      'counter-reset',
      'counter-increment',
      'resize',
      'cursor',
      'pointer-events',
      'speak',
      'user-select',
      'nav-index',
      'nav-up',
      'nav-right',
      'nav-down',
      'nav-left',
    ],
  },
];

module.exports = {
  plugins: ['stylelint-order'],
  rules: {
   'order/properties-order': [
      [...PROPERTY_ORDER],
      {
        unspecified: 'bottomAlphabetical',
        emptyLineBeforeUnspecified: 'threshold',
        emptyLineMinimumPropertyThreshold: 4,
      },
    ],
  },
};
```

Example stylesheet (SCSS):
```scss
.test-style {
  position: fixed;
  display: none;
  top: 0;                   // Stylelint: Expected an empty line before property "top" (order/order-properties-order)
  right: 0;
  bottom: 0;
  left: 0;
  background-color: black;  // Stylelint: Expected an empty line before property "background-color" (order/order-properties-order)
  z-index: 10;              // Stylelint: Expected an empty line before property "z-index" (order/order-properties-order)
}
```

I also tried to rule out the possibility that I might misunderstand the threshold by setting `100` as `emptyLineMinimumPropertyThreshold`, but I got the same errors.

With `emptyLineBefore: 'never'` the errors disappear as expected. But I want an empty line between the groups if there are more than 3 properties given for that group.
