### ISSUE TITLE
Order for custom properties?

### ISSUE THREAD

**Issue by hgl** [hudochenkov/stylelint-order#104]
It seems that there is no option to sort custom properties. Is it an intentional decision or it's planned?

**Comment by hudochenkov** [comment]
I'm not sure if sorting custom properties is a safe operation and it won't break resulting CSS.

**Comment by hgl** [comment]
@hudochenkov thanks for the quick reply.

Do you happen to know any case where it can break? I just checked the csswg, it doesn't seem to mention anything about order being important.

**Comment by hudochenkov** [comment]
I don't have experience with custom properties, so I don't know of any cases when the order matters.

**Comment by larsenwork** [comment]
I don't think the order is important — e.g. this
```CSS
:root {
  --width: 40px;
  --max-width: calc(50vw - var(--width));
}
```
and this
```CSS
:root {
  --max-width: calc(50vw - var(--width));
  --width: 40px;
}
```
does the exact same thing. 

Let's say one would have alphabetic sorting then `--max-width` would be first but since it uses `--width` it seems a bit weird.

Not sure I'd ever want my custom props sorted but maybe I'm just missing a good use case.

**Comment by hgl** [comment]
I’m in the hope that they might compress better, just like why you’d want to sort regular properties.

**Comment by felixfbecker** [comment]
I have a use case where I'd really like to order custom declarations, and I'd like to order them by their _value_ (with natural sorting). The use case is I have a file with all the z-indexes of the app defined as custom properties, and I'd like to have them in order to make it easy to see how they will stack. Example:
```scss
/* stylelint-enable order/order */
:root {
    --z-index-panel: 1;
	--z-index-autocomplete: 2;
 	--z-index-tooltip: 3;
}
```
