### ISSUE TITLE
disable @include with a block (order/order)stylelint(order/order)

### ISSUE THREAD

**Issue by zilahir** [hudochenkov/stylelint-order#106]
How can I disable this rule? 

![image](https://user-images.githubusercontent.com/6687149/74019349-26a27f00-49a0-11ea-995c-74291cc2d679.png)

**Comment by hudochenkov** [comment]
Check you configuration, and reconfigure order in a way you like.

**Comment by zilahir** [comment]
@hudochenkov thanks for your reply! 

Yeah, i tried, but can't seem to get the configuration ready. Would you give me a suggestion please?

**Comment by hudochenkov** [comment]
Show me your config, and tell me order you want for all things.

**Comment by zilahir** [comment]
```
{
  "extends": "@zilahir/stylelint-config",
  "ignoreFiles": ["**/*.js", "**/*.jsx"],
  "rules": {
    "order/properties-alphabetical-order": null,
    "selector-class-pattern": "[a-z]+((\\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?",
    "plugin/rational-order": null,
    "selector-max-compound-selectors": 4,
    "order-order": [
      {
        "type": "at-rule",
        "name": "include",
        "hasBlock": "true"
      }
    ]
  }
}
```

as you can see, in the `order/order` is the way i was playing with the settings. 

The only thing i want is not to get error for the following

```css
.topHeaderContainer {
	@include paragraph {
		font-size: 0;
	}
        @include something;
	background: rgba($color: $header-bg-color, $alpha: 0.7);
	position: fixed;
	height: $hader-height;
	width: 100%;
	display: flex;
	justify-content: space-between;
	align-items: center;
	transform: none;
	transition: all 200ms ease-in;
       ...
}
```
