### ISSUE TITLE
Custom sort mixins between properties

### ISSUE THREAD

**Issue by peiblox** [hudochenkov/stylelint-order#107]
Let's have this use case.
```scss
.foo {
    cursor: pointer;
    width: 100px;
    position: relative;
    font-family: sans-serif;
    @include fontSize(30);
    text-align: center;
    height: 100px;
}
```

With this config

```json
{
  "rules": {
    "order/order": [
      "custom-properties",
      "dollar-variables",
      "declarations",
      "at-rules",
      "rules"
    ],
    "order/properties-order": [
      "position",
      "width",
      "height",
      "font-family",
      "text-align",
      "cursor"
    ]
  }
}
```
It results in the following.

```scss
.foo {
    position: relative;
    width: 100px;
    height: 100px;
    font-family: sans-serif;
    text-align: center;
    cursor: pointer;

    @include fontSize(30);
}
```

If I have the following config, I manage to order all the properties just fine, but I can't maintain the @include mixin between the properties. I can order it before or after the properties, but I can't order it in the _fonts_ section.

I can change the `at-rules` position, or split them to sort some `at-rules` before the declarations and some after them.

Is there some way to add that @include in the config to stay after the `font-family` such as the following?

```json
{
  "rules": {
    "order/order": [
      "custom-properties",
      "dollar-variables",
      "declarations",
      "at-rules",
      "rules"
    ],
    "order/properties-order": [
      "position",
      "width",
      "height",
      "font-family",
      "@include fontSize",
      "text-align",
      "cursor"
    ]
  }
}
```

The result would be this.

```scss
.foo {
    position: relative;
    width: 100px;
    height: 100px;
    font-family: sans-serif;
    @include fontSize(30);
    text-align: center;
    cursor: pointer;
}
```

This behavior may extend to other custom mixins related to other properies, such as `size($width, $height)` or similar.
