### ISSUE TITLE
Add option `noEmptyLineBetween` to prevent empty lines between properties within a configured group

### ISSUE THREAD

**Issue by thasmo** [hudochenkov/stylelint-order#11]
The given rule
```json
{
	"emptyLineBefore": "always",
	"noEmptyLineBetween": true,
	"properties": [
		"position",
		"display"
	]
}
```
will show a warning for this: (the empty line should be removed)
```css
p {
	position: relative;

	display: block;
}
```
but will be fine i.e. ignore this: (current behavior without the new option anyway)
```css
p {
	position: relative;
	display: block;
}
```

**Comment by hudochenkov** [comment]
Thank you for suggestion! It seems legit because I can't find a way to configure `declaration-empty-line-before` so it won't be conflicted with `declaration-block-property-groups-structure`.

**Comment by ACVis** [comment]
So, is there any way to accomplish this currently? It seems like I can get it so that stylelint/stylelint-order apply --fix so that my code is separated into ordered groups such as below:

`
.test {
	position: relative;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;

	width: 100px;
	height: 100px;
	padding-top: 2rem;
	padding-bottom: 2rem;
	margin: 1rem;

	font-weight: 400;
	font-size: 16px;
	font-family: serif;
}
`

But then if I add spaces between them such as this:

`
.test {
	position: relative;

	top: 0;

	right: 0;

	bottom: 0;

	left: 0;

	width: 100px;

	height: 100px;

	padding-top: 2rem;

	padding-bottom: 2rem;

	margin: 1rem;

	font-weight: 400;

	font-size: 16px;

	font-family: serif;
}
`

It will not fix or give a warning in the above case. 

And there is no way to first apply something like `declaration-empty-line-before: false` to remove spaces and then to order by group and therefore then apply `emptyLineBefore: always`? Or will it do that but then always be giving you an error one way or another?

Also, I apologize, I can't seem to get Markdown to show my code correctly, but I think you can get the point.

**Comment by hudochenkov** [comment]
@ACVis Try to put `order/properties-order` after `declaration-empty-line-before` in your config. I'm not sure in which order `stylelint` runs rules, but maybe it will help.

**Comment by jeddy3** [comment]
> And there is no way to first apply something like `declaration-empty-line-before: false`

You can use either the [`"never"` primary option](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-empty-line-before#never) or the `"always"` primary option [_with the `except: ["after-declaration", "first-nested"]` secondary options_](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-empty-line-before#except-after-comment-after-declaration-first-nested) to remove the empty lines.

> Try to put order/properties-order after declaration-empty-line-before in your config. I'm not sure in which order stylelint runs rules, but maybe it will help.

It'll be interesting to know if this works. @ACVis Please report back if you can.

**Comment by ACVis** [comment]
Thank you everyone, I will try this and report back.

**Comment by ACVis** [comment]
Well, for a while I found a workaround to this problem issue by setting up a gulp file to watch every time I made a save and then run csscomb to properly format the file and then have stylelint fix the rest. But csscomb cannot handle anything beyond basic scss syntax and crashes the whole gulp process with fatal errors. So that does not work anymore. 

@jeddy3 Is there another workaround for this? Or would something needed to be added to this plugin or to stylelint itself? It's not in my skillset, but I would be willing to develop something for this, if necessary. Of course, I don't even know where the change should be made, or how.

**Comment by hudochenkov** [comment]
@ACVis Show your input CSS and what result you want to get, please.

**Comment by ACVis** [comment]
My initial instinct is to think that stylelint-order plugin needs a `spacesBetweenProperties` option.
`spacesBetweenProperties: "never"` would remove spaces between properties. Then I would think `declaration-empty-line-before: null` would allow this to happen with no warnings.


With a ruleset like this:

```yaml
"order/properties-order": [
         [
        {
          emptyLineBefore: "always",
          "order": "strict",
          properties: [
            "position",
            "z-index",
            "top",
            "right",
            "bottom",
            "left",
            "float",
            "clear"
          ],
        },
        {
          emptyLineBefore: "always",
          "order": "strict",
          properties: [
            "display",
            "visibility",
            "opacity"
          ],
        },
        {
          emptyLineBefore: "always",
          "order": "strict",
          properties: [
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
          ],
        },
      ]
    ],
```

And css such as this:

```css
.test {
	position: absolute;

	top: 1px;

	right: 1px;

	bottom: 1px;

	left: 1px;

	display: block; //there should be no newlines between display and opacity declarations

	opacity: 0;

	padding: 1rem; //there should be no newlines between these declarations below

	padding-top: 0;

	padding-bottom: 0;

	margin: 1rem;
}
```



then what I want to get is this:

```css
.test {
	position: absolute;
	top: 1px;
	right: 1px;
	bottom: 1px;
	left: 1px;

	display: block; //there should be no newlines between display and opacity declarations
	opacity: 0;

	padding: 1rem; //there should be no newlines between these lines below
	padding-top: 0;
	padding-bottom: 0;
	margin: 1rem;
}
```

If I have `"declaration-empty-line-before": "never",` then I will get that result, but line 8 `display: block;` and line 11 `padding: 1rem;` will give me this warning: `Unexpected empty line before declaration (declaration-empty-line-before)`. It's not my intention to never have an empty line before, I DO want empty lines before declaration groups, but that's the only rule setting that will organize my code.

If I have `"declaration-empty-line-before": null,` then the declarations will not be properly grouped because technically there is a newline before display and a newline before padding. So stylelint-order believes that everything is fixed as intended. But the problem is not that there is not newline before my intended group, the problem is that it is not organized as a group because there are newlines between declarations.
