### ISSUE TITLE
Vendor Prefix Ordering

### ISSUE THREAD

**Issue by webdevnerdstuff** [hudochenkov/stylelint-order#113]
Not really an issue, but  more of a question and/or feature request.

Is it possibly to allow the alpha sorting to allow vendor prefixed properties before the regular properties? I couldn't find it anywhere in the documentation.

Ex.
```scss
.foo {
    -webkit-margin-start: 0;
    color: #333;
    font-size: 1em;
    font-weight: bold;
    margin-left: 2px;
    position: relative;
}
```

**Comment by hudochenkov** [comment]
No, it's not possible. Prefixes are ignored for sorting.

You'll get this, because `-webkit-margin-start` sorted as `margin-start`:

```
.foo {
    color: #333;
    font-size: 1em;
    font-weight: bold;
    margin-left: 2px;
    -webkit-margin-start: 0;
    position: relative;
}
```

However, of there is a property both prefixed and unprefixed, prefixed one will be in the beginning:

```
.foo {
    margin-left: 2px;
    -webkit-margin-start: 0;
    margin-start: 0;
    position: relative;
}
```

**Comment by webdevnerdstuff** [comment]
There are VS Code extensions that do sort it in this manner. I would say it's more of a matter of adding the functionality or making it an added feature/option. By no means am I saying that's easy, as I'm not sure I could even figure it out. I looked at your source code for a minute before my head exploded thinking maybe I could give it a shot. :)

This VS Code Extension does sort a list in this way (for example).
https://github.com/Tyriar/vscode-sort-lines

That plugins sorts the following example:
```scss
.foo {
    display: block;
    -webkit-padding-start: initial;
    color: #fff;
    -webkit-animation: alternate;
}
```
To:
```scss
.foo {
    -webkit-animation: alternate;
    -webkit-padding-start: initial;
    color: #fff;
    display: block;
}
```

**Comment by hudochenkov** [comment]
That plugin doesn't know anything about CSS. In general special symbols like `-` go before letter in sort functions in JavaScript and everywhere else. That's why you see this behavior.

With behavior like this in CSS you'll get:

```css
.foo {
	-webkit-transform: none;
    color: #fff;
    display: block;
	transform: none;
}
```

`transform` in two different places rather be together.

I'm afraid such behavior will not be added to `stylelint-order`.
