### ISSUE TITLE
Order selectors, at-sign etc. outside of declaration blocks

### ISSUE THREAD

**Issue by thernstig** [hudochenkov/stylelint-order#135]
First, great plugin! :)

I was just wondering if there has been any thought about adding ordering of things outside of declaration blocks?

E.g. this:

```css
.zection {
  padding: var(--space-large) var(--space-large);
}

.section {
  padding: var(--space-large) var(--space-large);
}

@media only screen and (min-width: 480px) {
  .layout {
    grid-template-columns: 1fr;
  }
}
```

Would instead get sorted with `--fix` to become:

```css
@media only screen and (min-width: 480px) {
  .layout {
    grid-template-columns: 1fr;
  }
}

.section {
  padding: var(--space-large) var(--space-large);
}

.zection {
  padding: var(--space-large) var(--space-large);
}
```

In other words we can chose to order at-sign first in the file. And the rest in alphabetical order.
I am not sure if this would be of any value really, but thought I'd bring it up anyway.

**Comment by hudochenkov** [comment]
There is no value in this, in my opinion. Also, it could break CSS.

This makes `.a` blue on a screen 480px:

```css
@media only screen and (min-width: 480px) {
  .a {
    color: red;
  }
}

.a {
	color: blue;
}
```

This makes `.a` red on a screen 480px:

```css
.a {
	color: blue;
}

@media only screen and (min-width: 480px) {
  .a {
    color: red;
  }
}
```

Order is important here.

This plugin tries to report and fix things where order is not important for browser.
