### ISSUE TITLE
Support for CSS Modules / composes

### ISSUE THREAD

**Issue by christianvuerings** [hudochenkov/stylelint-order#14]
Would be great if we could support CSS Modules, especially the [`composes` rules](https://github.com/css-modules/css-modules#composition).

```css
.common {
  composes: no-border from global;
  border-radius: 4px;
}
```

currently fails with

```
✖  Expected border-radius to come before composes   order/declaration-block-properties-alphabetical-order
```

if we have the following config:

```
"order/declaration-block-order": [
    "custom-properties",
    "declarations"
],
"order/declaration-block-properties-alphabetical-order": true,
```
