### ISSUE TITLE
Using threshold with yaml

### ISSUE THREAD

**Issue by MartinDelille** [hudochenkov/stylelint-order#151]
I'm wondering how is it possible to use the threshold feature using a configuration file written in YAML ?

I tried to convert the \[configuration example\](https://github.com/hudochenkov/stylelint-order/tree/master/rules/properties-order#emptylineminimumpropertythreshold) to this converter but the JSON is considered invalid: [https://www.json2yaml.com/](https://www.json2yaml.com/)

Thank you in advance for your help!

**Comment by hudochenkov** [comment]
Indeed there is an extra comma if read that code as JSON and not JavaScript.

YAML of that example:

```yaml
---
order/properties-order:
- - emptyLineBefore: threshold
    properties:
    - display
  - emptyLineBefore: threshold
    properties:
    - height
    - width
  - emptyLineBefore: always
    properties:
    - border
  - emptyLineBefore: never
    properties:
    - transform
- unspecified: bottom
  emptyLineBeforeUnspecified: threshold
  emptyLineMinimumPropertyThreshold: 4

```
