### ISSUE TITLE
Support Glob or Regex in Properties' Order

### ISSUE THREAD

**Issue by movahhedi** [hudochenkov/stylelint-order#190]
Hello,
Can Glob/Regex/Minimatch support be added for `order/properties-order`.`properties`?

Example:
```json
{
    "order/properties-order": [
        [
            {
                "groupName": "all",
                "emptyLineBefore": "threshold",
                "noEmptyLineBetween": true,
                "properties": [
                    "float",
                    "width",
                    "*-width",
                    "height",
                    "*-height",
                    "padding",
                    "padding-*",
                    "margin",
                    "margin-*",
                    "overflow",
                    "overflow-*",
                ]
            }
        ]
    ]
}
```

**Comment by hudochenkov** [comment]
It would make order unreliable.

For example, both of these examples would pass linting with your config:

```css
a {
	padding-inline: 10px;
	padding-left: 20px;
	padding-right: 30px;
}

a {
	padding-right: 30px;
	padding-left: 20px;
	padding-inline: 10px;
}
```
