### ISSUE TITLE
Plugin complaining about blockless at-rule, even though it has one

### ISSUE THREAD

**Issue by Nirazul** [hudochenkov/stylelint-order#26]
Hey there! I'm running into an error with following configuration:

```js
module.exports = {
  'plugins': [
    'stylelint-order'
  ],
  'rules': {
    'order/order': [
      'dollar-variables',
      {
        type: 'at-rule',
        hasBlock: false,
      },
      'declarations',
      'rules',
    ],
  }
};
```

The code:
```scss
@mixin type--h1 {
    @include ff--base-bold;
    font-size: 3.0rem;

    &:not(:last-child) {
        margin-bottom: 28px;
    }

    @include mq('<=sm') {
        font-size: 2.6rem;
    }
}
```

The complaint:
```log
   9:5  error  Expected blockless at-rule to come before rule         order/order
```

It seems that the rule is misinterpreted as blockless even though it has one. The problem does not occur when I change the configuration to contain also at-rules with blocks. However, I don't want to restrict where to write them.
