### ISSUE TITLE
Bug when sorting properties & variables

### ISSUE THREAD

**Issue by igoradamenko** [hudochenkov/stylelint-order#47]
Hi!

I have a problem with autofix. When I have this stylesheet:

```scss
.test {
  $var: 0;
  
  left: 0;
  top: 0;
}
```

And stylelint config like this:

```json
{
  "plugins": [
    "stylelint-order"
  ],
  "rules": {
    "order/properties-order": [
      "top",
      "left"
    ]
  }
}
```

After running `stylelint --fix` I get:

```scss
.test {
  $var: 0;
  top: 0;

  left: 0;
}
```

But I've expected to get:

```scss
.test {
  $var: 0;

  top: 0;
  left: 0;
}
```

Is it a bug, or I should to update my stylelint config by adding some rules?
