### ISSUE TITLE
Grouping properties by separator

### ISSUE THREAD

**Issue by tenorok** [hudochenkov/stylelint-order#48]
Hello, thank you for helpful project!

Is it possible to break a solid list of properties by groups?

Let's Consider the example, for this config:
```json
{
    "plugins": [
        "stylelint-order"
    ],
    "rules": {
        "order/properties-order": [
            ["position", "top", "right", "bottom", "left"],
            ["margin", "display", "width", "height", "padding"]
        ],
        "order/groups-separator": "\n"
    }
}
```

It's will be the result with empty line between two groups:
```css
.foo {
    position: absolute;
    top: 0;
    bottom: 0;

    display: block;
    padding: 10px;
}
```

Do we have appropriate option in config now?
