### ISSUE TITLE
Alphabetical order exception for overriding shorthand declaration?

### ISSUE THREAD

**Issue by spaceninja** [hudochenkov/stylelint-order#50]
When I have `order/properties-alphabetical-order` I get a conflict with the following code:

```css
.foo {
    border-color: red;
    border-bottom-color: yellow;
}
```

If I sort alphabetically, then the bottom border color gets overridden by the shorthand. Is there a way to resolve this?
