### ISSUE TITLE
Properties with prefixes ignored when defined in group object

### ISSUE THREAD

**Issue by danahartweg** [hudochenkov/stylelint-order#53]
When only the base property is defined in the group object in the `properties` key, any rules with that prefix are seemingly ignored by the plugin. Is this just the nature of using group objects to define sets of ordered properties?

Given:

```javascript
[{
  emptyLineBefore: "true",
  order: "strict",
  properties: [
    "font",
    "color",
  ],
}]
```

The following will not present an error:

```css
div {
  display: block;

  color: black;
  font-weight: 500;
}
```
