### ISSUE TITLE
Don't apply properties-alphabetical-order autofixing if there no violations

### ISSUE THREAD

**Issue by pentzzsolt** [hudochenkov/stylelint-order#59]
With the `properties-alphabetical-order` set to `true`, the following code will throw no errors:

```
.a {
  color: #000;
  padding: {
    bottom: 1em;
    top: 1em;
  }
  width: 25%;
}
```

However, the `--fix` flag will scramble the code to the following:

```
.a {
   color: #000;
   width: 25%;
   padding: {
      bottom: 1em;
      top: 1em;
   }
}
```

Stylelint version `8.4.0`, stylelint-order version `0.8.0`.

**Comment by hudochenkov** [comment]
This is happening because `padding: {}` treated as at-rule by SCSS parser. There is nothing I can do about it. I would suggest refactoring code to:

```css
.a {
  color: #000;
  padding-bottom: 1em;
  padding-top: 1em;
  width: 25%;
}
```
