### ISSUE TITLE
--fix with order/order sometimes moves unspecified nodes to bottom

### ISSUE THREAD

**Issue by lee-chase** [hudochenkov/stylelint-order#60]
Using Stylelint --fix with stylelint-config-sass-guidelines results in unspecified nodes sometimes being moved to the bottom of a block;

e.g. This will not result in an order change
```scss
.a {
  $blue: #00f;
  border: 1px solid $blue;

  @mixin hi() {
    display: block;
    z-index: 99;
  }

  .b {
    @include hi;
  }
}
```

However, moving $blue down one line, moves both the variable declaration and the @mixin.

```scss
.a {
  border: 1px solid $blue;
  $blue: #00f;

  @mixin hi() {
    display: block;
    z-index: 99;
  }

  .b {
    @include hi;
  }
}
```

Resulting in 
```scss
.a {
  $blue: #00f;
  border: 1px solid $blue;

  .b {
    @include hi;
  }

  @mixin hi() {
    display: block;
    z-index: 99;
  }
}
```

**Comment by hudochenkov** [comment]
First example, does follow [the config](https://github.com/bjankord/stylelint-config-sass-guidelines/blob/ff104af541b38861af2ff9440fc394e4c11f2ddb/index.js#L38-L59). No violations would be reported, so autosorting doesn't kick in.

Second example do violate config, so autosorting kicks in. All undefined items always goes after defined items. `@mixin` doesn't defined in config, that's why it goes to the end.

You can overwrite `order/order` in your config. So you can use rule config from that shared config and add `@mixin`, so it always at the right place:

```json
{
	"rules": {
		"order/order": [
			"custom-properties",
			"dollar-variables",
			{
				"type": "at-rule",
				"name": "extend"
			},
			{
				"type": "at-rule",
				"name": "include",
				"hasBlock": false
			},
			{
				"type": "at-rule",
				"name": "mixin",
				"hasBlock": false
			},
			"declarations",
			{
				"type": "at-rule",
				"name": "include",
				"hasBlock": true
			},
			{
				"type": "at-rule",
				"name": "mixin",
				"hasBlock": true
			},
			"rules"
		]
	}
}
```

I've added `mixin` twice for when it has block, and when it's hasn't. Similar to `@include` config.

**Comment by lee-chase** [comment]
Understand this fully, spent quite a bit of my afternoon trying to understand why one config with did re-order but another did not. Took a while to hone in on an example as stylelint-property-sort-order-smaccs uses v0.6.0 (a good reason for this to go v1 some time as ^0 means there are multiple versions in my node_modules).

I agree that unspecified items should go at the bottom, just think it should always happen as @mixin is undefined and should violate the rules.

That said the code in v0.8.0 in rules/order/index.js has the following:

```js
// By default, ignore unspecified properties
const unspecified = _.get(options, 'unspecified', 'ignore');
```

P.S. Personally think functions, mixins, includes as an order, interested as to why you chose the other way round.

```js
   "rules": {
    "order/order": [
      [
        "custom-properties",
        "dollar-variables",
        {
          "type": "at-rule",
          "name": "extend"
        },
        {
          "type": "at-rule",
          "name": "function"
        },
        {
          "type": "at-rule",
          "name": "mixin",
          "hasBlock": false
        },
        {
          "type": "at-rule",
          "name": "include",
          "hasBlock": false
        },
        "declarations",
        {
          "type": "at-rule",
          "name": "mixin",
          "hasBlock": true
        },
        {
          "type": "at-rule",
          "name": "include",
          "hasBlock": true
        },
        "rules"
      ]
    ],
    "order/properties-alphabetical-order": true
  }
```

**Comment by hudochenkov** [comment]
> a good reason for this to go v1 some time as ^0 means there are multiple versions in my node_modules

Indeed. API is quite stable now.

> I agree that unspecified items should go at the bottom, just think it should always happen as @mixin is undefined and should violate the rules.

When we check order (not fixing), we can ignore undefined things. But when fixing — it's impossible to ignore, because we're changing position of items before and after undefined thing. We can't ignore undefined thing, as it should have place. So we have only two options when fixing — put before (`'order/order': [['rules'], { unspecified: 'top'}]]`) or after (`'order/order': [['rules'], { unspecified: 'bottom'}]]`) specified items.

> P.S. Personally think functions, mixins, includes as an order, interested as to why you chose the other way round.

Sorry, I didn't understood that part.

**Comment by lee-chase** [comment]
In order/order you suggested this order: custom-properties, dollar-variables,  @includes without block, @mixins without block, declarations, @includes with blocks, @mixins with block.

Typically I declare @functions before @mixins and @mixins before @includes, mostly because I tend to declare before use. Your suggestion would place @mixins after @includes. Just interested to know if that was a deliberate choice or just an example.

**Comment by lee-chase** [comment]
Thinking about this further, in SCSS @if, @each etc all need to be left in place and would never have a specified position. As a result, I now think moving any unspecified is a bug.

Moving @if to the end in the following example is a change in function. I now find myself having to check every fix manually, or not use --fix at all.

```scss
@mixin blue-border($light: false) {
  $blue: #00f;

  @if $light == true {
    $blue: #44f;
  }

  border: 1px solid $blue;
}

.a {
  @include blue-border(false);
}

.b {
  @include blue-border(true);
}
```

**Comment by hudochenkov** [comment]
> Just interested to know if that was a deliberate choice or just an example.

It was just example. On projects, where I use PostCSS only, there is a [postcss-mixins](https://github.com/postcss/postcss-mixins) plugin, which have `@mixin` (similar to Sass `@include`) and `@define-mixin` (similar to Sass `@mixin`).

> Another thought, can @Mixins be declared without a block?

Sure. I don't think it's possible to have `@mixin` without a block (`{}`), so here is an example for `@include`:

```js
[
    // Matches @include with block only
    // @include name {}
    {
        type: 'at-rule',
        name: 'include',
        hasBlock: true
    },
    // Matches @include without block only
    // @include name;
    {
        type: 'at-rule',
        name: 'include',
        hasBlock: false
    },
    // Matches all @include regardless of block
    // @include name {}
    // @include name;
    {
        type: 'at-rule',
        name: 'include'
    }
]
```

> Moving @if to the end in the following example is a change in function. I now find myself having to check every fix manually, or not use --fix at all.

Given:

```json
{
  "rules": {
    "order/order": [
      "dollar-variables",
      "declarations",
      {
        "type": "at-rule",
        "name": "media"
      }
    ]
  }
}
```

Input:

```scss
@mixin blue-border($light: false) {
  $blue: #00f;

  position: absolute;
  box-shadow: 2px 2px 2px $blue;
  
  @if $light == true {
    $blue: #44f;
  }

  @media (min-width: 400px) {
    background: #ccc;
  }

  display: block;
  border: 1px solid $blue;
}
```

Desired result:

```scss
@mixin blue-border($light: false) {
  $blue: #00f;

  position: absolute;
  box-shadow: 2px 2px 2px $blue;
  
  @if $light == true {
    $blue: #44f;
  }

  display: block;
  border: 1px solid $blue;

  @media (min-width: 400px) {
    background: #ccc;
  }
}
```

Actual result:

```scss
@mixin blue-border($light: false) {
  $blue: #00f;

  position: absolute;
  box-shadow: 2px 2px 2px $blue;

  display: block;
  border: 1px solid $blue;

  @media (min-width: 400px) {
    background: #ccc;
  }

  @if $light == true {
    $blue: #44f;
  }
}
```

It's impossible to know how to sort this complex example without human or very sophisticated program.

No tools should be used to sort logic. CSS doesn't have logic, so it's safe to sort. If styles written for preprocessors they ideally should not contain logic as well, in my opinion.

It's about knowing tools limitation. `stylelint-order` will not be aware of a logic that might be written in a style sheet. Please, proceed with caution when using it against files with logic (`if` statements, loops, etc.). Unfortunately, it's not possible at the moment to ignore part of a file for `--fix` like it's possible for regular linting.
