### ISSUE TITLE
Fixed order *within* flexible order?

### ISSUE THREAD

**Issue by jsit** [hudochenkov/stylelint-order#64]
Say I want this to be valid:

```css
div {
  margin: 0;
  margin-top: 10px;
  margin-right: 20px;
  padding: 0;
}
```

And I want this to be valid:

```css
div {
  padding: 0;
  margin: 0;
  margin-top: 10px;
  margin-right: 20px;
}
```

But I want this to be invalid:

```css
div {
  padding: 0;
  margin-right: 20px;
  margin: 0;
  margin-top: 10px;
}
```

In other words, I don't care whether `padding` or `margin` comes first, but I always want any `margin` properties to be in the same order.

The config might look something like this:
```javascript
[
  {
    "properties": [
      {
        "properties": [
          "padding", "padding-top", "padding-right", "padding-bottom", "padding-left"
        ]
      },
      {
        "properties": [
          "margin", "margin-top", "margin-right", "margin-bottom", "margin-left"
        ]
      },
    ],
    "order": "flexible"
  }
]
```

This doesn't work, of course, but could something like it be made to work?
