### ISSUE TITLE
empty line before for order

### ISSUE THREAD

**Issue by AndyOGo** [hudochenkov/stylelint-order#66]
I would like to force separation of keyword-related syntax by newlines.

**Good:**

```css
.foo {
  @at-rule no-block();
  @at-rule no-block();

  display: block;
  text-align: left;

  span {}

  @at-rule with-block() {
     // ...
  }
}
```

**Bad:**

```css
.foo {
  @at-rule no-block();
  @at-rule no-block();
  display: block;
  text-align: left;
  span {}
  @at-rule with-block() {
     // ...
  }
}
```
