### ISSUE TITLE
Ignore the case characters order

### ISSUE THREAD

**Issue by evanre** [hudochenkov/stylelint-order#78]
Hi, I've got a specific problem.
I'm trying to implement stylelint into my environment (which is for development newsletters and based on Foundation for Emails). There is specific hacks for developing newsletters for legacy email clients. And one of them is margins support in Outlook. It requires to use a "margin" property with first capital letter.
For example - `Margin: 0 auto;`, so the total style block looks like this: 
```css
.publications {
        display: block;
        margin: 0 auto 5px 0;
        Margin: 0 auto 5px 0;
        width: auto;
}
```
It's necessary to capital "Margin" follows after lower one. But in this case I'm getting alphabetical error. I suppose there is a some regexp that looks like [A-Za-z]. Is there any chance to change this behavior?

Thanks
