### ISSUE TITLE
'Unexpected an empty line before property "undefined"'

### ISSUE THREAD

**Issue by jamesarosen** [hudochenkov/stylelint-order#87]
Given this stylelint configuration:
```js
'order/properties-order': [
  [
    'color',
    'font-size',
  ],
  {
    unspecified: 'bottom',
    emptyLineBeforeUnspecified: 'never',
  },
]
```
and the following SCSS:
```scss
.foo {
  color: blue;
  font-size: 12px;

  &__bar {
    color: purple;
  }
}
```

I get the following error:
```
   5:3  ✖  Unexpected an empty line before property "undefined"            order/properties-order
```
