### ISSUE TITLE
Bug: Using stylelint-order with --fix flag ignores /* stylelint-disable-next-line */

### ISSUE THREAD

**Issue by JimDrury** [hudochenkov/stylelint-order#89]
Using stylelint-order with --fix flag ignores /* stylelint-disable-next-line */ when order/properties-alphabetical-order is set to true.

```css
.class {
    border-width: 1px;

    /* stylelint-disable-next-line */
    border-bottom-width: 0;
}
```

Becomes:

```css
.class {
    /* stylelint-disable-next-line */
    border-bottom-width: 0;

    border-width: 1px;
}
```
