### ISSUE TITLE
at rule in scss

### ISSUE THREAD

**Issue by nathanredblur** [hudochenkov/stylelint-order#94]
```SCSS
@function em($pixels, $base: $base--font-size) {
  @if (unitless($pixels)) {
    $pixels: $pixels * 1px;
  }

  @if (unitless($base)) {
    $base: $base * 1px;
  }
  
  @return ($pixels / $base) * 1em;
}
```

Error: `10:3  ✖  Expected at-rule to come before at-rule with a block   order/order`
