### ISSUE TITLE
Doesn't fix empty strings after sorting

### ISSUE THREAD

**Issue by mishanga** [hudochenkov/stylelint-order#95]
Before autofix:
```css
.Divider {
    height: 100%;

    width: 100%;
}
```

After autofix:
```css
.Divider {

    width: 100%;
    height: 100%;
}
```

Config:
```js
module.exports = {
    "plugins": [
        "stylelint-order",
    ],
    "rules": {
        "order/properties-order": [
            {
                "emptyLineBefore": "always",
                "properties": [
                    "width",
                    "height",
                ],
            },
        ],
    },
};
```

Versions:
```
stylelint@9.10.1
stylelint-order@2.2.1
```
